services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.local
    container_name: venture-launch-frontend
    networks:
      - venture-launch-network
    env_file: ./.env.local
    ports:
      - ${INTERNAL_FRONTEND_PORT}:3000
    volumes:
      - ./frontend/src:/app/src

  nginx:
    image: nginx:latest
    container_name: venture-launch-nginx
    networks:
      - venture-launch-network
    env_file: ./.env.local
    ports:
      - ${INTERNAL_NGINX_PORT}:80
    volumes:
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf
    expose:
      - ${INTERNAL_NGINX_PORT}
    depends_on:
      - frontend
    restart: unless-stopped

networks:
  venture-launch-network:
    driver: bridge
